before_script: 
- cd server
- npm install codeclimate-test-reporter istanbul -g
language: node_js
node_js:
   - "stable"
addons:
   code_climate:
     repo_token: a315018021e648cae168bcf040a0809f041d9806
script:
  - npm install && npm run test
  - make test-coveralls
  - istanbul cover node_modules/mocha/bin/_mocha -- -R spec
after_script: 
- "cat
./coverage/lcov.info |
./node_modules/coveralls/bin/coveralls.js"
- codeclimate-test-reporter < ./coverage/lcov.info